### ISSUE TITLE
SimpleHttpResponse使用有点不方便

### ISSUE THREAD

**Issue by Andyfoo** [94fzb/simplewebserver#1]
renderJson 使用了固定的json库是不行的，应该给用户传字符串的方法。
renderByMimeType 应该弄成public的，方便用户扩展输出类型。
我自己在com.hibegin.http.server.impl.SimpleHttpResponse增加了个renderString，content-type我自己定义
```
	
	public void renderString(String body) {
		try {
			send(buildResponseData(200, body.getBytes(responseConfig.getCharSet())));
		} catch (Exception e) {
			LOGGER.log(Level.SEVERE, "", e);
		}
	}
```

**Comment by 94fzb** [comment]
@Andyfoo 谢谢，gson 的确是应该搞成可以配置的，理论上不会覆盖 content-type 的

![image](https://user-images.githubusercontent.com/12691281/45766531-690fd280-bc6a-11e8-8d4d-64a8ef952b2a.png)

这个地方应该先检查是否有在业务代码里面放置 content-type，如果没有才根据文件后缀进行识别，算是个 bug
