### ISSUE TITLE
是否可以像nginx一样，将整个目录render,比如我使用JCEF开发，需要一个简单的http服务器用来展示HTML

### ISSUE THREAD

**Issue by endsock** [94fzb/simplewebserver#5]
是否可以像nginx一样，将整个目录render,比如我使用JCEF开发，一个简单的http服务器，但是必须用java，如何实现类似于nginx的功能，只是为了展示html以及关联的CSS,JS

**Comment by 94fzb** [comment]
现在就是有的，如果仅现能正常渲染一个静态的 html 网站还是比较简单的，serverConfig.addStaticResourceMapper 方法可以把实现的，无论是读取 jar 外的文件还是 jar，只是默认是读取 jar 内的文件的，如果需要读取类似 /var/html/www 这种外部文件目录进行渲染使用。StaticResourceLoader 自己实现具体的文件读取就可以啦  @endsock

**Comment by endsock** [comment]
好的，多谢了

**Comment by endsock** [comment]
> addStaticResourceMapper

我看您写了一个LocalFileStaticResourceLoader，是否是实现这个功能的，可否直接使用？

**Comment by 94fzb** [comment]
@endsock 可以直接使用，但是建议用 serverConfig.addLocalFileStaticResourceMapper 这个方法，两个参数的是可直接渲染一个文件夹下的静态资源，3个参数的，第三个参数主要用来实现简单文件共享服务的。类似 nginx location 里面的 autoIndex on 的效果的

https://github.com/94fzb/simplewebserver/blob/master/src/test/java/com/hibegin/http/server/test/LocalFileStaticMapperApplication.java 可以参数这个示例

**Comment by 94fzb** [comment]
@endsock 可以直接使用，但是建议用 serverConfig.addLocalFileStaticResourceMapper 这个方法，两个参数的是可直接渲染一个文件夹下的静态资源，3个参数的，第三个参数主要用来实现简单文件共享服务的。类似 nginx location 里面的 autoIndex on 的效果的

**Comment by endsock** [comment]
已使用，感谢作者，麻烦将这个版本发布到中央仓库

**Comment by 94fzb** [comment]
已发布，使用 0.3.142
