### ISSUE TITLE
运行不起来，不支持JDK1.8了吗？

### ISSUE THREAD

**Issue by 350078238** [94fzb/simplewebserver#6]
"C:\Program Files\Java\jdk1.8.0_191\bin\java.exe" "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2\lib\idea_rt.jar=8824:D:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_191\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\rt.jar;F:\JAVA\MusicPlay\target\classes;C:\Users\ASUS\.m2\repository\com\hibegin\simplewebserver\0.3.142\simplewebserver-0.3.142.jar" controller.IndexController
Exception in thread "main" java.lang.NoSuchMethodError: java.net.URLDecoder.decode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;
	at com.hibegin.http.server.util.PathUtil.getRootPath(PathUtil.java:39)
	at com.hibegin.http.server.util.PathUtil.getLogPath(PathUtil.java:106)
	at com.hibegin.common.util.LoggerUtil.getLogFilePath(LoggerUtil.java:77)
	at com.hibegin.common.util.LoggerUtil.buildFileHandle(LoggerUtil.java:32)
	at com.hibegin.common.util.LoggerUtil.getLogger(LoggerUtil.java:62)
	at com.hibegin.http.server.config.ServerConfig.<clinit>(ServerConfig.java:21)
	at controller.IndexController.main(IndexController.java:11)

Process finished with exit code 1

**Comment by 94fzb** [comment]
看起来是 java nio 的库可能有调整的，尝试兼容下得

**Comment by 94fzb** [comment]
的确是不支持了 java8 了，使用 145，这个版本，理论上是兼容了 java8 了

**Comment by 350078238** [comment]
> 的确是不支持了 java8 了，使用 145，这个版本，理论上是兼容了 java8 了

谢谢，他这个文档也没有说明下  重要依赖，那就换个 别的用吧

**Comment by 94fzb** [comment]
0.3.145 是支持 java8 的，可以试下，如果有问题可以反馈。
不过都  2024， 没必要固守 java8 ，java8 他已经老了
